%define tl_version 2011
%define tl_noarch_release 9
%define _binary_payload w6.xzdio

%{!?_texdir: %global _texdir %{_datadir}/texlive}

%define __perl_requires %{nil}
%define __os_install_post /usr/lib/rpm/brp-compress %{nil}
%define __debug_install_post %{nil}

Source0: ftp://ftp.ctex.org/mirrors/texlive/tlpretest/archive/montex.tar.xz
Source1: ftp://ftp.ctex.org/mirrors/texlive/tlpretest/archive/montex.doc.tar.xz

Name: texlive-montex
License: GPL+
Summary: Mongolian LaTeX
Version: %{tl_version}
Release: %{tl_noarch_release}.IVu.04.092.svn17853%{?dist}
BuildArch: noarch
Requires: texlive-base = %{tl_version}
Requires: texlive-kpathsea-bin = %{tl_version}
Requires: texlive-tetex-bin = %{tl_version}
Requires(post,postun): texlive-tetex-bin = %{tl_version}
Requires(post,postun): texlive-kpathsea-bin = %{tl_version}
Requires: texlive-cbfonts = %{tl_version}
Provides: tex(mls.sty)
Provides: tex(rlbicig.sty)
Requires: tex(ifthen.sty)
Requires: tex(diagnose.sty)
Requires: tex(fontenc.sty)
Requires: tex(inputenc.sty)
Requires: tex(rotating.sty)
Requires: tex(lscape.sty)
Requires: texlive-montex-fedora-fonts = %{tl_version}

%description
MonTeX provides Mongolian and Manju support for the TeX/LaTeX
community. Mongolian is a language spoken in North East Asia,
namely Mongolia and the Inner Mongol Autonomous Region of
China. Today, it is written in an extended Cyrillic alphabet in
Mongolia whereas the Uighur writing continues to be in use in
Inner Mongolia, though it is also, legally speaking, the
official writing system of Mongolia. Manju is another language
of North East Asia, belonging to the Tungusic branch of the
Altaic languages. Though it is hardly spoken nowadays, it
survives in written form as Manju was the native language of
the rulers of the Qing dynasty (1644-1911) in China. Large
quantities of documents of the Imperial Archives survive, as
well as some of the finest dictionaries ever compiled in Asia,
like the Pentaglot, a dictionary comprising Manju, Tibetan,
Mongolian, Uighur and Chinese. MonTeX provides all necessary
characters for writing standard Mongolian in Cyrillic and
Classical (aka Traditional or Uighur) writing, and Manju as
well as transliterated Tibetan texts, for which purpose a
number of additional characters was created. In MonTeX, both
Mongolian and Manju are entered in romanized form. The
retransliteration (from Latin input to Mongolian and Manju
output) is completely realized in TeX/Metafont so that no
external preprocessor is required. Please note that most of the
enhanced functions of MonTeX require a working e-LaTeX
environment. This is especially true when compiling documents
with Mongolian or Manju as the main document language. It is
recommended to choose pdfelatex as the resulting PDF files are
truly portable. Vertical text generated by MonTeX is not
supported in DVI.

date: 2010-04-09 16:33:31 +0200

%post
mkdir -p /var/run/texlive
touch /var/run/texlive/run-texhash
echo "MixedMap mongolian.map" >> %{_texdir}/texmf/web2c/updmap.cfg
touch /var/run/texlive/run-updmap
:

%postun
if [ $1 == 0 ]; then
  sed -i '/^MixedMap mongolian.map/d' %{_texdir}/texmf/web2c/updmap.cfg
  %{_bindir}/texhash 2> /dev/null
  %{_bindir}/updmap-sys --nohash --quiet &> /dev/null
else
  mkdir -p /var/run/texlive
  touch /var/run/texlive/run-texhash
  touch /var/run/texlive/run-updmap
fi
:

%posttrans
[ -e /var/run/texlive/run-texhash ] && %{_bindir}/texhash 2> /dev/null && rm -f /var/run/texlive/run-texhash
[ -e /var/run/texlive/run-updmap ] && %{_bindir}/updmap-sys --nohash --quiet &> /dev/null && rm -f /var/run/texlive/run-updmap
[ -e /var/run/texlive ] && rm -rf /var/run/texlive
:

%package doc
Summary: Documentation for montex
Version: %{tl_version}
Release: %{tl_noarch_release}.IVu.04.092.svn17853%{?dist}
Requires: texlive-base = %{tl_version}
BuildArch: noarch
Requires: texlive-cbfonts-doc

%description doc
Documentation for montex

%package fedora-fonts
Summary: Fonts for montex
Version: %{tl_version}
Release: %{tl_noarch_release}.IVu.04.092.svn17853%{?dist}
Requires: fontpackages-filesystem
BuildRequires: fontpackages-devel
Requires: texlive-montex = %{tl_version}
BuildArch: noarch

%description fedora-fonts
MonTeX provides Mongolian and Manju support for the TeX/LaTeX
community. Mongolian is a language spoken in North East Asia,
namely Mongolia and the Inner Mongol Autonomous Region of
China. Today, it is written in an extended Cyrillic alphabet in
Mongolia whereas the Uighur writing continues to be in use in
Inner Mongolia, though it is also, legally speaking, the
official writing system of Mongolia. Manju is another language
of North East Asia, belonging to the Tungusic branch of the
Altaic languages. Though it is hardly spoken nowadays, it
survives in written form as Manju was the native language of
the rulers of the Qing dynasty (1644-1911) in China. Large
quantities of documents of the Imperial Archives survive, as
well as some of the finest dictionaries ever compiled in Asia,
like the Pentaglot, a dictionary comprising Manju, Tibetan,
Mongolian, Uighur and Chinese. MonTeX provides all necessary
characters for writing standard Mongolian in Cyrillic and
Classical (aka Traditional or Uighur) writing, and Manju as
well as transliterated Tibetan texts, for which purpose a
number of additional characters was created. In MonTeX, both
Mongolian and Manju are entered in romanized form. The
retransliteration (from Latin input to Mongolian and Manju
output) is completely realized in TeX/Metafont so that no
external preprocessor is required. Please note that most of the
enhanced functions of MonTeX require a working e-LaTeX
environment. This is especially true when compiling documents
with Mongolian or Manju as the main document language. It is
recommended to choose pdfelatex as the resulting PDF files are
truly portable. Vertical text generated by MonTeX is not
supported in DVI.

date: 2010-04-09 16:33:31 +0200


%prep
%setup -q -c -T

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{_texdir}/texmf-dist
ln -s %{_texdir}/licenses/gpl.txt gpl.txt
xz -dc %{SOURCE0} | tar x -C %{buildroot}%{_texdir}/texmf-dist
xz -dc %{SOURCE1} | tar x -C %{buildroot}%{_texdir}/texmf-dist
# nuke useless tlmgr packaging stuff and doc droppings
rm -rf %{buildroot}%{_texdir}/tlpkg/tlpobj/
rm -rf %{buildroot}%{_texdir}/texmf-dist/tlpkg/tlpobj/
rm -rf %{buildroot}%{_texdir}/texmf/doc/man/man*/*.pdf
rm -rf %{buildroot}%{_texdir}/texmf/doc/man/Makefile
rm -rf %{buildroot}%{_texdir}/texmf/doc/man/man*/Makefile
rm -rf %{buildroot}%{_texdir}/texmf/doc/info/dir

# link installed fonts with Fedora
install -d -m 0755 %{buildroot}%{_fontdir}
pushd %{buildroot}%{_fontdir}
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghsb.pfb .
ln -s %{_fontdir}/bcghsb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghsb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghsm.pfb .
ln -s %{_fontdir}/bcghsm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghsm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghwb.pfb .
ln -s %{_fontdir}/bcghwb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghwb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghwm.pfb .
ln -s %{_fontdir}/bcghwm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghwm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvsb.pfb .
ln -s %{_fontdir}/bcgvsb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvsb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvsm.pfb .
ln -s %{_fontdir}/bcgvsm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvsm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvwb.pfb .
ln -s %{_fontdir}/bcgvwb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvwb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvwm.pfb .
ln -s %{_fontdir}/bcgvwm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvwm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicighb.pfb .
ln -s %{_fontdir}/bicighb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicighb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicighm.pfb .
ln -s %{_fontdir}/bicighm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicighm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicigvb.pfb .
ln -s %{_fontdir}/bicigvb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicigvb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicigvm.pfb .
ln -s %{_fontdir}/bicigvm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bicigvm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhsb.pfb .
ln -s %{_fontdir}/bthhsb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhsb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhsm.pfb .
ln -s %{_fontdir}/bthhsm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhsm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhwb.pfb .
ln -s %{_fontdir}/bthhwb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhwb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhwm.pfb .
ln -s %{_fontdir}/bthhwm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhwm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvsb.pfb .
ln -s %{_fontdir}/bthvsb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvsb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvsm.pfb .
ln -s %{_fontdir}/bthvsm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvsm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvwb.pfb .
ln -s %{_fontdir}/bthvwb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvwb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvwm.pfb .
ln -s %{_fontdir}/bthvwm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvwm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghsb.pfb .
ln -s %{_fontdir}/bxghsb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghsb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghsm.pfb .
ln -s %{_fontdir}/bxghsm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghsm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghwb.pfb .
ln -s %{_fontdir}/bxghwb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghwb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghwm.pfb .
ln -s %{_fontdir}/bxghwm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghwm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvsb.pfb .
ln -s %{_fontdir}/bxgvsb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvsb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvsm.pfb .
ln -s %{_fontdir}/bxgvsm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvsm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvwb.pfb .
ln -s %{_fontdir}/bxgvwb.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvwb.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvwm.pfb .
ln -s %{_fontdir}/bxgvwm.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvwm.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/kmbx10.pfb .
ln -s %{_fontdir}/kmbx10.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/kmbx10.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/kmr10.pfb .
ln -s %{_fontdir}/kmr10.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/kmr10.pfb
mv %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/kmss10.pfb .
ln -s %{_fontdir}/kmss10.pfb %{buildroot}%{_texdir}/texmf-dist/fonts/type1/public/montex/kmss10.pfb
popd
%_font_pkg -n fedora *

%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root)
%doc gpl.txt
%{_texdir}/texmf-dist/fonts/map/dvips/montex/mongolian.map
%{_texdir}/texmf-dist/fonts/source/public/montex/bcghsb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcghsm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcghwb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcghwm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcgvsb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcgvsm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcgvwb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bcgvwm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bicighb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bicighm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bicigvb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bicigvm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthhsb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthhsm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthhwb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthhwm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthvsb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthvsm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthvwb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bthvwm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxghsb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxghsm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxghwb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxghwm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxgvsb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxgvsm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxgvwb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/bxgvwm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/cyrmorec.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/cyrmorei.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/cyrmorel.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/cyrmoreu.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmb10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx5.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx6.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx7.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbx9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbxsl10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmbxti10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmcsc10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmcsc8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmcsc9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmdunh10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmff10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmfi10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmfib8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kminch.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmitt10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr17.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr5.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr6.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr7.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmr9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmsl10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmsl12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmsl8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmsl9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmsltt10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmss10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmss12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmss17.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmss8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmss9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssbx10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssdc10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssi10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssi12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssi17.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssi8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssi9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssq8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmssqi8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmtcsc10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmti10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmti12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmti7.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmti8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmti9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmtt10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmtt12.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmtt8.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmtt9.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmu10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmvtt10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/kmvtti10.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/lmligs.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/macodes.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/maglyphs.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mantrlig.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbatoms.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbcodes.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbglyphs.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbligtbl.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbnums.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbparmb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbparmm.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbparms.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mbpunc.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcccscco.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mccoding.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mctextit.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyccsc.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyitall.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyrill.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyrl.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyrligs.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyrsymb.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcyru.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mcytitle.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mlscodes.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mocodes.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/moglyphs.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/montrlig.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mxcodes.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mxglyphs.mf
%{_texdir}/texmf-dist/fonts/source/public/montex/mxntrlig.mf
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcghsb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcghsm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcghwb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcghwm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcgvsb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcgvsm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcgvwb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bcgvwm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bicighb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bicighm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bicigvb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bicigvm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthhsb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthhsm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthhwb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthhwm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthvsb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthvsm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthvwb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bthvwm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxghsb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxghsm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxghwb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxghwm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxgvsb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxgvsm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxgvwb.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/bxgvwm.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmb10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx5.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx6.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx7.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbx9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbxsl10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmbxti10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmcsc10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmcsc8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmcsc9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmdunh10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmff10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmfi10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmfib8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kminch.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmitt10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr17.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr5.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr6.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr7.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmr9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmsl10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmsl12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmsl8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmsl9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmsltt10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmss10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmss12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmss17.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmss8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmss9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssbx10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssdc10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssi10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssi12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssi17.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssi8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssi9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssq8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmssqi8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmtcsc10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmti10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmti12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmti7.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmti8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmti9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmtt10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmtt12.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmtt8.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmtt9.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmu10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmvtt10.tfm
%{_texdir}/texmf-dist/fonts/tfm/public/montex/kmvtti10.tfm
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghsb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghsm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghwb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcghwm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvsb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvsm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvwb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bcgvwm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bicighb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bicighm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bicigvb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bicigvm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhsb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhsm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhwb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthhwm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvsb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvsm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvwb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bthvwm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghsb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghsm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghwb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxghwm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvsb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvsm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvwb.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/bxgvwm.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/kmbx10.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/kmr10.pfb
%{_texdir}/texmf-dist/fonts/type1/public/montex/kmss10.pfb
%{_texdir}/texmf-dist/tex/latex/montex/bicig.def
%{_texdir}/texmf-dist/tex/latex/montex/bithe.def
%{_texdir}/texmf-dist/tex/latex/montex/buryat.def
%{_texdir}/texmf-dist/tex/latex/montex/cpctt.def
%{_texdir}/texmf-dist/tex/latex/montex/cpdbk.def
%{_texdir}/texmf-dist/tex/latex/montex/cpibmrus.def
%{_texdir}/texmf-dist/tex/latex/montex/cpkoi.def
%{_texdir}/texmf-dist/tex/latex/montex/cpmls.def
%{_texdir}/texmf-dist/tex/latex/montex/cpmnk.def
%{_texdir}/texmf-dist/tex/latex/montex/cpmos.def
%{_texdir}/texmf-dist/tex/latex/montex/cpncc.def
%{_texdir}/texmf-dist/tex/latex/montex/english.def
%{_texdir}/texmf-dist/tex/latex/montex/kazakh.def
%{_texdir}/texmf-dist/tex/latex/montex/lmabthhs.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmabthhw.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmabthvs.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmabthvw.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmaenc.def
%{_texdir}/texmf-dist/tex/latex/montex/lmccmdh.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmfib.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmfr.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmiss.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmr.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmss.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmssq.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmtt.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmccmvtt.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmcenc.def
%{_texdir}/texmf-dist/tex/latex/montex/lmclcmss.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmobcghs.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmobcghw.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmobcgvs.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmobcgvw.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmoenc.def
%{_texdir}/texmf-dist/tex/latex/montex/lmsbcgh.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmsbcgv.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmsenc.def
%{_texdir}/texmf-dist/tex/latex/montex/lmubxghs.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmubxghw.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmubxgvs.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmubxgvw.fd
%{_texdir}/texmf-dist/tex/latex/montex/lmuenc.def
%{_texdir}/texmf-dist/tex/latex/montex/mls.sty
%{_texdir}/texmf-dist/tex/latex/montex/mlsgalig.tex
%{_texdir}/texmf-dist/tex/latex/montex/mlstrans.tex
%{_texdir}/texmf-dist/tex/latex/montex/mnhyphex.tex
%{_texdir}/texmf-dist/tex/latex/montex/rlbicig.sty
%{_texdir}/texmf-dist/tex/latex/montex/russian.def
%{_texdir}/texmf-dist/tex/latex/montex/xalx.def

%files doc
%defattr(-,root,root)
%doc gpl.txt
%{_texdir}/texmf-dist/doc/latex/montex/00README
%{_texdir}/texmf-dist/doc/latex/montex/00readme.mfinput.km
%{_texdir}/texmf-dist/doc/latex/montex/ANNOUNCE
%{_texdir}/texmf-dist/doc/latex/montex/EMTEX
%{_texdir}/texmf-dist/doc/latex/montex/HISTORY
%{_texdir}/texmf-dist/doc/latex/montex/INSTALL
%{_texdir}/texmf-dist/doc/latex/montex/MIKTEX
%{_texdir}/texmf-dist/doc/latex/montex/TODO
%{_texdir}/texmf-dist/doc/latex/montex/UPDATE
%{_texdir}/texmf-dist/doc/latex/montex/cyrename.pl
%{_texdir}/texmf-dist/doc/latex/montex/fontlist.tex
%{_texdir}/texmf-dist/doc/latex/montex/mkmlsmf.pl
%{_texdir}/texmf-dist/doc/latex/montex/mls-diag.tex
%{_texdir}/texmf-dist/doc/latex/montex/mlsquick.pdf
%{_texdir}/texmf-dist/doc/latex/montex/mlsquick.tex
%{_texdir}/texmf-dist/doc/latex/montex/mnhyphen.tex
%{_texdir}/texmf-dist/doc/latex/montex/montex.pdf
%{_texdir}/texmf-dist/doc/latex/montex/montex.tex
%{_texdir}/texmf-dist/doc/latex/montex/montex.xml
%{_texdir}/texmf-dist/doc/latex/montex/mtdocmac.tex
%{_texdir}/texmf-dist/doc/latex/montex/testfont.input
%{_texdir}/texmf-dist/doc/latex/montex/testfont.sh
%{_texdir}/texmf-dist/doc/latex/montex/zanabazr.pdf
%{_texdir}/texmf-dist/doc/latex/montex/zanabazr.tex
%{_texdir}/texmf-dist/doc/latex/montex/mfinput/bithe/testfont.input
%{_texdir}/texmf-dist/doc/latex/montex/mfinput/bithe/testfont.sh

%files fedora-fonts
%defattr(-,root,root)
%dir %{_fontdir}
%{_fontdir}/bcghsb.pfb
%{_fontdir}/bcghsm.pfb
%{_fontdir}/bcghwb.pfb
%{_fontdir}/bcghwm.pfb
%{_fontdir}/bcgvsb.pfb
%{_fontdir}/bcgvsm.pfb
%{_fontdir}/bcgvwb.pfb
%{_fontdir}/bcgvwm.pfb
%{_fontdir}/bicighb.pfb
%{_fontdir}/bicighm.pfb
%{_fontdir}/bicigvb.pfb
%{_fontdir}/bicigvm.pfb
%{_fontdir}/bthhsb.pfb
%{_fontdir}/bthhsm.pfb
%{_fontdir}/bthhwb.pfb
%{_fontdir}/bthhwm.pfb
%{_fontdir}/bthvsb.pfb
%{_fontdir}/bthvsm.pfb
%{_fontdir}/bthvwb.pfb
%{_fontdir}/bthvwm.pfb
%{_fontdir}/bxghsb.pfb
%{_fontdir}/bxghsm.pfb
%{_fontdir}/bxghwb.pfb
%{_fontdir}/bxghwm.pfb
%{_fontdir}/bxgvsb.pfb
%{_fontdir}/bxgvsm.pfb
%{_fontdir}/bxgvwb.pfb
%{_fontdir}/bxgvwm.pfb
%{_fontdir}/kmbx10.pfb
%{_fontdir}/kmr10.pfb
%{_fontdir}/kmss10.pfb

%changelog
* Mon Aug 23 2010 Jindrich Novy <jnovy@redhat.com> 2010-9
- rpmlint fixes

* Sat Jul 17 2010 Jindrich Novy <jnovy@redhat.com> 2010-8
- depend on the new texlive-base noarch package
- ship licenses with documentation
- sync with upstream

* Mon May 31 2010 Jindrich Novy <jnovy@redhat.com> 2010-7
- switch to "tlpretest" source tree
- add lua and ruby dependencies to packages requiring them
- generate global package database "texlive.tlpdb" directly from
tlpobj files shipped with each package

* Wed May 19 2010 Jindrich Novy <jnovy@redhat.com> 2010-6
- update to the latest frozen development TeX Live
- add svn to noarch versions according to guildelines

* Fri Apr 30 2010 Jindrich Novy <jnovy@redhat.com> 2010-5
- add dependencies resolution among biblatex files
- another %%postun scriplets fix

* Wed Apr 21 2010 Jindrich Novy <jnovy@redhat.com> 2010-4
- fix and tighten dependencies in %%post* scriptlets
- extract dependencies also from .cls and .ldf files
- speed up build by skipping some bits in __os_install_post

* Mon Apr 19 2010 Jindrich Novy <jnovy@redhat.com> 2010-3
- speed up installation/updating by running updmap/fmtutil
and texhash post-transaction once

* Sat Apr 03 2010 Jindrich Novy <jnovy@redhat.com> 2010-0.1
- bump version to 2010
- reduce total number of packages from 3580 to 3440 by removal
of dummy ones not shipping actually anything
- add style dependencies from packages reecently added
(were previously blacklisted)
- do not ship koma-script sources

* Tue Nov 10 2009 Jindrich Novy <jnovy@redhat.com> 2009-4
- info and man pages are now part of main packages, not -doc
- use fedora-compliant license codes for License in spec
- fix fedora-fonts packages generation
- add dummy description if packages misses any
- package bdf fonts

* Tue Nov 10 2009 Jindrich Novy <jnovy@redhat.com> 2009-2
- install man and info pages into proper locations visible
by man and info
- update scriptlets
- remove xindy bits

* Mon Nov 09 2009 Jindrich Novy <jnovy@redhat.com> 2009-1
- official TeX Live 2009 release

* Tue Aug 25 2009 Jindrich Novy <jnovy@redhat.com> 2009-0.3
- make TeX Live TrueType and OpenType fonts accessible by
other Fedora apps

* Thu Aug 20 2009 Jindrich Novy <jnovy@redhat.com> 2009-0.2
- don't package generated pdfs from man pages

* Wed Aug 12 2009 Jindrich Novy <jnovy@redhat.com> 2009-0.1
- initial packaging for TeX Live 2009
